Tanta/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from dashboard import views
from peer2peer import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views

urlpatterns =[
    url(r'^admin/', admin.site.urls),
    url(r'^',include("home_page.urls",namespace='home_page')),
    url(r'^dashboard/',include("dashboard.urls",namespace='dashboard')),
    url(r'^accounts/login/$',views.login,name='login'),
    url(r'^accounts/logout/$',views.logout,name='logout',kwargs={'next_page':'/'}),
    url(r'^wallet/',include("wallet.urls",namespace="wallet")),
    url(r'^peer2peer/',include("peer2peer.urls",namespace="p2p")),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

peer2peer/urls.py
from django.conf.urls import url
from peer2peer import views

urlpatterns=[
	url(r'^$',views.p2p,name='p2phome'),
]

wallet/urls.py
from django.conf.urls import url
from wallet import views

urlpatterns=[
	url(r'^$',views.wallet_summary,name="wallet_summary"),
	url(r'^transfer/$',views.transfer,name='transfer'),
	url(r'^info/$',views.info,name='info'),
	url(r'^forex/$',views.forex,name='forex'),
	url(r'^settings/$',views.settings,name='settings'),
	url(r'^contacts/$',views.contacts,name='contacts'),
	url(r'^peer2peer/$',views.p2p,name='p2p'),
	url(r'^groups/$',views.groups,name='groups'),
	url(r'^contacts/add/$',views.add_contacts,name='add_contact'),
	url(r'^info/reset/$',views.passreset,name='pword'),
	url(r'^groups/display_groups/$',views.display_groups,name='display_groups'),
	url(r'^contacts/verify/$',views.send_contacts,name='verify_contact'),
	url(r'^groups/group_limit/$',views.group_limit,name='group_limit'),
	url(r'^groups/remove/$',views.group_remove,name='group_remove'),
	url(r'^groups/create/$',views.create_group,name='group_create'),
	url(r'^contacts/details/$',views.contact_detail,name='contact_detail'),
	url(r'^contacts/remove/$',views.contact_remove,name='contact_remove'),

]

wallet/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.validators import RegexValidator
# Create your models here.
currencies=(
	('USD','United States Dollar'),
	('GBP','British Pound'),
	('EUR','Euro'),
	('GHS','Ghanaian Cedi'),)
group_types=(
	('borrow'),
	('lend'))

class Wallet(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	dollars=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	euros=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	pounds=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	cedis=models.DecimalField(default=0,decimal_places=2,max_digits=9)


	
###### WRITE METHODS FOR TRANSACTIONS: EG VERIFY USER, CHECK AMOUNT, ETC. #####
	def grab_values(self,sender,recipient,currency):
		if sender == recipient:
			return "Can't Send Money to yourself!"
		if currency=='USD':
				sender_start=sender.dollars
				recipient_start=recipient.dollars
		elif currency=='EUR':
			sender_start=sender.euros
			recipient_start=recipient.euros
		elif currency=='GBP':
			sender_start=sender.pounds
			recipient_start=recipient.pounds
		elif currency=='GHS':
			sender_start=sender.cedis
			recipient_start=recipient.cedis

		return sender_start, recipient_start

	def grab_forex(self,user,currency):
		if currency=='USD':
				user_start=user.dollars
		elif currency=='EUR':
			user_start=user.euros
		elif currency=='GBP':
			user_start=user.pounds
		elif currency=='GHS':
			user_start=user.cedis
		return user_start

	
	def transaction_send(self,sender_start,amount):
		if sender_start < amount:
			return "Insufficient Funds"
		else:
			sender_final=sender_start - amount
		return sender_final
	
	def transaction_recieve(self,recipient_start,amount):
		recipient_final=recipient_start + amount
		return recipient_final
	
	def commit_transaction(self,sender,recipient,currency,sender_final,recipient_final):
		if currency=='USD':
			sender.dollars=sender_final
			recipient.dollars=recipient_final
		elif currency=='EUR':
			sender.euros=sender_final
			recipient.euros=recipient_final
		elif currency=='GBP':
			sender.pounds=sender_final
			recipient.pounds=recipient_final
		elif currency=='GHS':
			sender.cedis=sender_final
			recipient.cedis=recipient_final
		self.save()

	def commit_forex(self,user,currency,user_amount):
		if currency=='USD':
			user.dollars=user_amount
		elif currency=='EUR':
			user.euros=user_amount
		elif currency=='GBP':
			user.pounds=user_amount
		elif currency=='GHS':
			user.cedis=user_amount
		self.save()



	def __str__(self):
		return str(self.user)

class TransactionsManager(models.Manager):
	def save_record(self,sender,reciever,amount, currency):
		self.create(sender=sender,fx='',reciever=reciever,amount=amount,currency=currency,transfer_date=timezone.now())
	def save_forex(self,fx,amount,currency,changed_amount,changed_currency):
		self.create(sender='', fx=fx,reciever='FX',amount=amount,currency=currency,changed_amount=changed_amount,
			changed_currency=changed_currency,transfer_date=timezone.now())


class Transactions(models.Model):
	sender=models.CharField(max_length=13)
	fx=models.CharField(max_length=13,null=True)
	reciever=models.CharField(max_length=13)
	amount=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	changed_amount=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	currency=models.CharField(max_length=5,null=True)
	changed_currency=models.CharField(max_length=5,null=True)
	transfer_date=models.DateTimeField(default=timezone.now)
	objects=TransactionsManager()

	class Meta:
		get_latest_by='transfer_date'

			

	def __str__(self):
		return str(self.sender) + " " +str(self.amount) +str(self.currency) + " " +str(self.reciever)

		

class ForexRates(models.Model):
	date=models.DateTimeField(default=timezone.now)
	dollars=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	euros=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	pounds=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	cedis=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	shillings=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	pesos=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	naira=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	swkrone=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	nwkrone=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	indrp=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	chny=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	ausd=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	saud=models.DecimalField(default=0,decimal_places=2,max_digits=9)
	rurub=models.DecimalField(default=0,decimal_places=2,max_digits=9)

	def grab_exchange_currency(self,currency):
		if currency=='USD':
				curr_return=self.dollars
		elif currency=='EUR':
			curr_return=self.euros
		elif currency=='GBP':
			curr_return=self.pounds
		elif currency=='GHS':
			curr_return=self.cedis
		return curr_return

	def convert_currency_to_dollar(self,currency_have,amount):
		if currency_have=='USD':
				curr_dollar=(1/self.dollars)*amount
		elif currency_have=='EUR':
			curr_dollar=(1/self.euros)*amount
		elif currency_have=='GBP':
			curr_dollar=(1/self.pounds)*amount
		elif currency_have=='GHS':
			curr_dollar=(1/self.cedis)*amount
		return curr_dollar

	def convert_currency_from_dollar(self,currency_want,curr_dollar):
		if currency_want=='USD':
				final_amount=(self.dollars)*curr_dollar
		elif currency_want=='EUR':
			final_amount=(self.euros)*curr_dollar
		elif currency_want=='GBP':
			final_amount=(self.pounds)*curr_dollar
		elif currency_want=='GHS':
			final_amount=(self.cedis)*curr_dollar
		return final_amount


	def __str__(self):
		return str(self.date)


class Settings(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	borrow_lend=models.BooleanField(default=False)
	

	def save_settings(self,user,borrow_lend):
		borrow_lend=user.borrow_lend
		self.save()
	
	def __str__(self):
		return str(self.user) + " " + "settings"

class Social(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	groups=models.ManyToManyField('Group')
	list_display=('groups')

	def __str__(self):
		return str(self.user)

class Group(models.Model):
	group_types=(
	('borrow','borrow'),
	('lend','lend'))
	name=models.CharField(max_length=200)
	group_type = models.CharField(max_length=6,choices=group_types,default='lend')
	class Meta:
		ordering=['name']
	def __str__(self):
		return str(self.name)


class GroupMember(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey('Group',null=True)
    
    def __str__(self):
        return '{} joined {}'.format(self.person,self.group)

class ContactsManager(models.Manager):
	def save_contact(self,user,contact,phone):
		self.create(user=user,name=contact,phone_number=phone)
	
class Contacts(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	name=models.CharField(max_length=150)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	phone_number = models.CharField(max_length=15,validators=[phone_regex], blank=True)
	objects=ContactsManager()

	def __str__(self):
		return str(self.name) + " " + str(self.user)

wallet/forms.py
from django import forms
from django.forms import ModelForm
from wallet.models import Wallet, currencies, Settings, GroupMember, Group



class TransferForm(forms.Form):
	amount=forms.DecimalField(min_value=1,decimal_places=2,label='',
		widget=forms.NumberInput(attrs={'placeholder':'Transfer Amount'}))
	recipient=forms.CharField(label='',required=False,
		widget=forms.TextInput(attrs={'placeholder':'Enter name or id'}))
		

class ForexForm(forms.Form):
	amount=forms.DecimalField(min_value=1,decimal_places=2,label='',
		widget=forms.NumberInput(attrs={'placeholder':'Exchange Amount'}))
	currency_want=forms.ChoiceField(currencies,label='')

class SettingsForm(forms.ModelForm):
	class Meta:
		model=Settings
		fields=['borrow_lend']

class ContactForm(forms.Form):
	contact_name=forms.CharField(label='',
		widget=forms.TextInput(attrs={'placeholder':'Enter name or phone #'}))
class GroupForm(forms.ModelForm):
	class Meta:
		model=Group
		fields=['name','group_type']
	def clean(self):
		cleaned_data=super().clean()
		name=self.cleaned_data['name']
		try:
			Group.objects.get(name=name)
			raise forms.ValidationError('Group already exists')
		except:
			pass

home_page/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from home_page.models import NewLead
from home_page.forms import NewLead,UserForm,UserProfileInfoForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.views.generic import (TemplateView,View,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.models import User
from django.conf import settings

# Create your views here.

# class IndexView(TemplateView):
# 	template_name='home_page/home.html'

def index(request):
	return render(request,'home_page/home.html')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home_page:index'))

def contact(request):
	form=NewLead(auto_id=False)
	if request.method=='POST':
		form=NewLead(request.POST)
		if form.is_valid():
			form.save(commit=True)
			return thanks(request)
	return render(request,'home_page/contact.html',{'form':form})

def about(request):
	return render(request,'home_page/about.html')

def thanks(request):
	return render(request,'home_page/thank_you.html')

def onyx(request):
	return render(request,'home_page/onyx.html')

def getstarted(request):
	registered=False

	if request.method =='POST':
		user_form =UserForm(data=request.POST)
		profile_form=UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():


			user=user_form.save()
			user.set_password(user.password)
			user.save()

			profile=profile_form.save(commit=False)
			profile.user=user
			profile.save()

			registered=True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form=UserForm()
		profile_form=UserProfileInfoForm()
		
	return render(request,'home_page/getstart.html',
		{'user_form':user_form,'profile_form':profile_form,
		'registered':registered})

def signin(request):
	if request.method == 'POST':
		username=request.POST.get('username','')
		password=request.POST.get('password','')
		user=authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('wallet:wallet_summary'))
			else:
				return HttpResponse('Account not active')
		else:
			return HttpResponse('User does not exist')
	else:
		return render(request,'home_page/sign_in.html')

wallet/templates/wallet/add_contact.html
{% extends "wallet/base.html" %}
{% block content %}
<div class="container">
<div class="center px2 py2 white bg-gray bg-cover bg-center rounded" style='background:#e5e5e5; box-shadow: 5px 5px 30px #888888;''>
    <form method="post">
{% csrf_token %}
{{form}}
<input type="hidden" name="next" value='{{ request.GET.next }}'>
<br>
<input type="submit" class="h3 p1 btn btn-success" value="Add Contact">
</form>
<script>
	$(document).ready(function(){
			$('#btn-submit').submit(
				mixpanel.track('Contact added'))
		
	});
</script>
</div>
</div>
{% endblock content %}

wallet/templates/wallet/base.html
<!DOCTYPE html>
{% load staticfiles %}
<link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Catamaran:800" rel="stylesheet"> 

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=News+Cycle" >
<link href="{% static 'js/jquery-3.2.1.min.js' %}">
<!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init("{{mixpanel}}");</script><!-- end Mixpanel -->
<script src="{% static 'js/jquery.avgrund.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/avgrund.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'css/bss.css' %}">
<script scr='{% static " js/myscript.js" %}'></script>
<html>
<head>
	<title>
		Welcome to Tanta Wallet
	</title>
</head>
<body>
<nav class="navbar navbar-default">
<div class="navbar-header">
</div>
	<ul id=navlist class="nav navbar-nav">
	
		<li><a class="navbar-link" href="{% url 'wallet:wallet_summary' %}">My Wallet</a></li>
		<li>
		<div class='realative inline block'>
			  <button type="button" class="btn btn-big mt1 p4" id='menu' style=" background-color: #f9f9f9;">
			    Actions &#9662;
			  </button>
			  <div class="clearfix" style="display: none; position: absolute; background-color: #f9f9f9;" id='dropdown-content'>
			    <a href="{% url 'wallet:transfer' %}" class="btn block" style='color: black;'>Transfer</a>
			    <a href="{% url 'wallet:forex' %}"" class="btn block" style='color: black;'>Currency Exchange</a>
			    <a href="{% url 'wallet:contacts' %}" class="btn block" style='color: black;'>Manage Contacts</a>
			    <a href="{% url 'p2p:p2phome' %}" class="btn block " style='color: black;'>Borrow or Lend</a>
			    <a href="{% url 'wallet:settings' %}?next={{ request.path|urlencode }}" class="btn block " style='color: black;'>Settings</a>
			  </div>
			</div></li>
		<li><a class="navbar-link" href="{% url 'wallet:info' %}">My Info</a></li>
		<li><a class= 'navbar-link' href="{% url 'dashboard:logout' %}">Sign Out</a></li>
		</ul>
		</nav>
<br>
</body>
<script>
	$(document).ready(function(){
		$('#menu').hover(function(){
			$('#dropdown-content').toggle();
			$('#dropdown-content').mouseenter(function(){
				$(this).show();
			});
			$('#dropdown-content').mouseleave(function(){
				$(this).hide();
			});
		});
	})
</script>
</html>
{% block content %}
{% endblock content %}

wallet/templates/wallet/forex_thanks.html
{% extends "wallet/base.html" %}
{% block content %}
<div class="container px2 py3">
<div class='clearfix mxn2'>
<h1 class="flex flex-auto">You exchanged:</h1>
<h3>{{amount}} {{ch}} for {{fc}} {{cw}}</h3>
<a class="btn btn-success" href="{% url 'wallet:wallet_summary' %}">Return to Wallet</a>

{% endblock content %}
</div>
</div>

 

wallet/templates/wallet/group_form.html
{% extends "wallet/base.html" %}
{% block content %}

<div class="center container">
<h2>Create a Group!</h2>
<h4>Get started by creating a borrowing or lending group and invite your friends to join!</h4>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input type="hidden" name="next" value='{{ request.GET.next }}'>
	<button type="submit" id='btn-submit'>Create</button>
</form>
<script>
	$(document).ready(function(){
			$('#btn-submit').submit(
				mixpanel.track('Group Created', {
					'group name': $('#id_name').val()
				})
				);
	});
</script>
</div>
{% endblock content %}

wallet/templates/wallet/group_remove.html
{% extends 'wallet/base.html' %}
{% load actview %}
{% block content %}
<div class="container">
<div class="center px2 py2 white bg-gray bg-cover bg-center rounded" style='background:#e5e5e5; box-shadow: 5px 5px 30px #888888;''>
<form method="post">
{% csrf_token %}
<h4 class='flex justify-center'>Choose a group type to leave:</h4>
<select name='group' id='group'>
{% for group in group_list %}
<option value="{{group.group}}">{{group.group}}</option>	
{% endfor %}
</select>
<input type="hidden" name="next" value='{{ request.GET.next }}'>
<input type="submit" class="mt4 h3 p1 btn btn-success" value="Leave" id='btn-submit'>
</form>
<script>
	$(document).ready(function(){
			$('#btn-submit').submit(
				mixpanel.track('User left group')
			});
</script>
</div>
</div>
{% endblock content %}

wallet/templates/wallet/groups.html
{% extends "wallet/base.html" %}
{% load static %}
{% block content %}
<div class="container">
<div class="center px2 py2 white bg-gray bg-cover bg-center rounded" style='background:#e5e5e5; box-shadow: 5px 5px 30px #888888;''>
<form method="post" data-show-groups-url="{% url 'wallet:display_groups'%}">
{% csrf_token %}
<h4 class='flex justify-center'>Choose a group type:</h4>
<select name='type' id='type'>
	<option value=""></option>
	<option value="borrow">Borrow</option>
	<option value="lend">Lend</option>
</select>
<select name='group' id='group' style="display: none;">
	
</select>
<input type="hidden" name="next" value='{{ request.GET.next }}'>
<input type="submit" class="mt4 h3 p1 btn btn-success" value="Join" id='btn-submit'>
</form>
</div>
</div>
<script>
	$(document).ready(function(){
			$('#btn-submit').submit(
				mixpanel.track('User joined group'));
		var form = $('form')
		$('#type').change(function(){
			$("#type option[value='']").remove();
			$.ajax({
			url:"{% url 'wallet:group_limit' %}",
			datatype: 'json',
			data: form.serialize(),
			success: function(data){
					var data_value = data
						if (data_value > 0){
						$('#btn-submit').prop('disabled',true);
					}
					else{$('#btn-submit').prop('disabled',false);}
				}
		});
			
			$.ajax({
				url:form.attr('data-show-groups-url'),
				datatype: 'json',
				data: form.serialize(),
				success: function(data){
					$('#group').empty()
					for (var i = 0; i < data.length; i++){
						$('#group')
						.append($("<option></option>")
						.attr('value',data.value)
						.text(data[i].fields.name));
					}
					$('h4').text('Choose the group you wish to join');
					$('#group').show();


				}
			});
		});
		
	});


</script>
{% endblock content %}

wallet/templates/wallet/insufficient.html
{% extends "wallet/base.html" %}
{% block content %}
   <h1>Insufficient Funds.</h1> 
{% endblock content %}

wallet/templates/wallet/invalid_user.html
{% extends "wallet/base.html" %}
{% block content %}
    <h1>Invalid User</h1>
<br>
<h3>Please go back and select a valid user id.</h3>
{% endblock content %}

wallet/templates/wallet/pword.html
{% extends "wallet/base.html" %}
{% block content %}
<div class="container">
<div class="center px2 py2 white bg-gray bg-cover bg-center rounded" style='background:#e5e5e5; box-shadow: 5px 5px 30px #888888;''>
    <form method="post">
    {% csrf_token %}
    	{{form.as_p}}
    	<input type="hidden" name="next" value='{{ request.GET.next }}'>
    	<input type="submit" class='btn btn-default' value="Change" style="background: #ff495c">
    </form>
    </div>
    </div>
{% endblock content %}

wallet/templates/wallet/self_send_error.html
{% extends "wallet/base.html" %}
{% block content %}
<h1>Can't send money to yourself!</h1>
<br>
<h2>Nice try.</h2>
    
{% endblock content %}

wallet/templates/wallet/transactions_list.html
{% load static %}
<div class="container px2 py3">
<div class='clearfix mxn2'>
<h2 class="h1 mb0">Recent Activity</h2>
<div class="flex flex-auto mxn2">

</div>
<div class="sm-col sm-col-4 ml-4">
    {% for transfer in sent %}

    <h5>Sent {{transfer.reciever}} {{transfer.amount}} {{transfer.currency}}</h5> on {{transfer.transfer_date|date:'M d, Y P e'}}
    {% endfor %}
    </div>
<div class="sm-col sm-col-4 ml-4">
    {% for transfer in received %}
     <h5><strong>Recieved</strong> {{transfer.amount}} {{transfer.currency}}</h5> from {{transfer.sender}} on {{transfer.transfer_date|date:'M d, Y P e'}}
     {% endfor %}
     </div>

<div class="sm-col sm-col-4 ml-4">
    {% for transfer in changed %}
    <h5>You changed {{transfer.amount}} {{transfer.currency}}</h5>
    to {{transfer.changed_amount}} {{transfer.changed_currency}} on {{transfer.transfer_date|date:'M d, Y P'}}

    {% endfor %}
    </div> 

</div>
</div>
</div>
</div>
</div>


    <div class='sm-flex center'>
<div class='flex-auto'>
<a class="h3 btn btn-success m2" id='fxbtn' href="{% url 'wallet:transfer' %}" role="button">Transfer Money</a></div>
<div class="flex-auto">
<a class="h3 btn btn-success m2" id='fxbtn' href="{% url 'wallet:forex' %}" role="button">Currency Exchange</a></div>
     </div>
</div>

wallet/templates/wallet/wallet_summary.html
{% extends "wallet/base.html" %}
{% load staticfiles %}
{% load actview %}
{% block content %}
<div class='flex justify-center'>
<div class='p2 m4-center'>
<h1 style="font-family: 'News Cycle';">Welcome, {{user.username}}!</h1>
</div>
</div>

<div class='container'>
<div class="flex flex-auto ml3 mt4" style="position: relative;"><h4>Your id is {{user.id}}</h4></div>
<div class="center px2 py2 white bg-gray bg-cover bg-center rounded" style='background:#e5e5e5; box-shadow: 5px 5px 30px #888888;'>
<h2>Your balances are:</h2>

<div class="container mx-auto">

<div class='col col-12 mx-auto'>
<ul class="list-reset flex justify-center">
{% show_wallet %}
</ul>

</div>
</div>

{% show_activity %}
<div class='center'>
<div class='col-6 mx-auto'>
<a class="h3 btn btn-success mx4 mb4 pb4" id='fxbtn' href="{% url 'wallet:transfer' %}" role="button">Transfer Money</a>

<a class="h3 btn btn-success mx4 mb4 pb4" id='fxbtn' href="{% url 'wallet:forex' %}" role="button">Currency Exchange</a></div>

<script>
	$(document).ready(function(){
		mixpanel.track('Wallet home loaded')
	})
</script>
{% endblock content %}