Tanta/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from dashboard import views
from peer2peer import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views

urlpatterns =[
    url(r'^admin/', admin.site.urls),
    url(r'^',include("home_page.urls",namespace='home_page')),
    url(r'^dashboard/',include("dashboard.urls",namespace='dashboard')),
    url(r'^accounts/login/$',views.login,name='login'),
    url(r'^accounts/logout/$',views.logout,name='logout',kwargs={'next_page':'/'}),
    url(r'^wallet/',include("wallet.urls",namespace="wallet")),
    url(r'^peer2peer/',include("peer2peer.urls",namespace="p2p")),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home_page/urls.py
from django.conf.urls import url
from home_page import views

app_name='home_page'

urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'contact/$',views.contact,name='contact'),
	url(r'^about/$',views.about,name='about'),
	url(r'^onyx/$',views.onyx,name='onyx'),
	url(r'^getstarted/$',views.getstarted,name='getstart'),
	url(r'^sign_in/',views.signin,name='sign_in'),
	url(r'^logout/$',views.user_logout,name='logout')
]

wallet/urls.py
from django.conf.urls import url
from wallet import views

urlpatterns=[
	url(r'^$',views.wallet_summary,name="wallet_summary"),
	url(r'^transfer/$',views.transfer,name='transfer'),
	url(r'^info/$',views.info,name='info'),
	url(r'^forex/$',views.forex,name='forex'),
	url(r'^settings/$',views.settings,name='settings'),
	url(r'^contacts/$',views.contacts,name='contacts'),
	url(r'^peer2peer/$',views.p2p,name='p2p'),
	url(r'^groups/$',views.groups,name='groups'),
	url(r'^contacts/add/$',views.add_contacts,name='add_contact'),
	url(r'^info/reset/$',views.passreset,name='pword'),
	url(r'^groups/display_groups/$',views.display_groups,name='display_groups'),
	url(r'^contacts/verify/$',views.send_contacts,name='verify_contact'),
	url(r'^groups/group_limit/$',views.group_limit,name='group_limit'),
	url(r'^groups/remove/$',views.group_remove,name='group_remove'),
	url(r'^groups/create/$',views.create_group,name='group_create'),
	url(r'^contacts/details/$',views.contact_detail,name='contact_detail'),
	url(r'^contacts/remove/$',views.contact_remove,name='contact_remove'),

]

home_page/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.
class NewLead(models.Model):
	name=models.CharField(max_length=40)
	email=models.EmailField(max_length=40)
	verify_email=models.EmailField(max_length=40)
	business=models.CharField(max_length=40)
	text=models.CharField(max_length=400)
	def __str__(self):
		return self.name

class UserProfileInfo(models.Model):
	user=models.OneToOneField(User)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	phone_number = models.CharField(max_length=15,validators=[phone_regex], blank=True)

	def __str__(self):
		return self.user.username

home_page/forms.py
from django import forms
from django.core import validators
from home_page.models import NewLead
from django.contrib.auth.models import User
from home_page.models import UserProfileInfo


class NewLead(forms.ModelForm):
	class Meta:
		model=NewLead
		fields='__all__'
		labels={
		''
		}
		widgets={
		'name' : forms.TextInput(attrs={'placeholder':'Name'}),
		'email': forms.TextInput(attrs={'placeholder':'Email'}),
		'verify_email':forms.TextInput(attrs={'placeholder':'Verify Email'}),
		'business':forms.TextInput(attrs={'placeholder':'Business Name'}),
		'text':forms.Textarea(attrs={'cols':100,'rows':10,'placeholder':'Describe your project. What problems are you facing? What ideas do you have?'})
		}
		
	def clean(self):
		all_clean_data=super().clean()
		email=all_clean_data['email']
		vmail=all_clean_data['verify_email']
		if email != vmail:
			raise forms.ValidationError("Make sure emails match")


class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model=User
		fields=('username','password')
	def clean_username(self):
		cleaned_data=super().clean()
		username=self.cleaned_data['username']
		if User.objects.filter(username__iexact=username):
		 	raise forms.ValidationError('Username taken')
		else:
			pass
		return username

class UserProfileInfoForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(UserProfileInfoForm, self).__init__(*args, **kwargs)
		self.fields['phone_number'].required = True
	class Meta():
		model=UserProfileInfo
		fields=['phone_number']

home_page/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from home_page.models import NewLead
from home_page.forms import NewLead,UserForm,UserProfileInfoForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.views.generic import (TemplateView,View,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.models import User
from django.conf import settings

# Create your views here.

# class IndexView(TemplateView):
# 	template_name='home_page/home.html'

def index(request):
	return render(request,'home_page/home.html')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home_page:index'))

def contact(request):
	form=NewLead(auto_id=False)
	if request.method=='POST':
		form=NewLead(request.POST)
		if form.is_valid():
			form.save(commit=True)
			return thanks(request)
	return render(request,'home_page/contact.html',{'form':form})

def about(request):
	return render(request,'home_page/about.html')

def thanks(request):
	return render(request,'home_page/thank_you.html')

def onyx(request):
	return render(request,'home_page/onyx.html')

def getstarted(request):
	registered=False

	if request.method =='POST':
		user_form =UserForm(data=request.POST)
		profile_form=UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():


			user=user_form.save()
			user.set_password(user.password)
			user.save()

			profile=profile_form.save(commit=False)
			profile.user=user
			profile.save()

			registered=True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form=UserForm()
		profile_form=UserProfileInfoForm()
		
	return render(request,'home_page/getstart.html',
		{'user_form':user_form,'profile_form':profile_form,
		'registered':registered})

def signin(request):
	if request.method == 'POST':
		username=request.POST.get('username','')
		password=request.POST.get('password','')
		user=authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('wallet:wallet_summary'))
			else:
				return HttpResponse('Account not active')
		else:
			return HttpResponse('User does not exist')
	else:
		return render(request,'home_page/sign_in.html')

home_page/templates/home_page/about.html
<!DOCTYPE html>
{% extends "home_page/base.html" %}
{% load staticfiles %}
{% block body_block %}
    

<div id=jumbo class="jumbotron">
<div class="container">
<h1>What we do</h1>
<h3>WALLET</h3>

<p>More than 2 billion of the world’s people are unbanked, primarily due to a lack of
access and high costs. At TantaPay, our mission is to get the entire world access to
financial services.</p>
<p>If you are a foreign worker looking to send money home to your family, a world
traveler looking for the easiest way to get foreign currency, a small business owner
looking to expand, or an ambitious saver looking for a place to put your savings to
work, we have a solution for you.</p>
<h3>TRANSFERS</h3>
<p class="sub">
TantaPay believes payments should be fast, easy, and secure, no matter where you
are. Send money to your family overseas instantly, and without big transaction fees.
Pay your friends, your taxi driver, or your favorite restaurant instantly, securely,
and without the need for a bulky wallet.</p>

<h3>FOREIGN EXCHANGE</h3>
<p class="sub">Change currencies when you’re traveling without the hassle or fees of a Foreign
Exchange bureau. Exchange as much or as little money as you want, when you want,
at current market rates, without exchange fees. When you’re home, change back to
your local currency with the same ease and convenience, or keep the foreign
currency until your next trip.</p>

<h3>LEND</h3>
<p class="sub">No matter how much money you have today, we believe that everyone should have
an opportunity to build wealth. At TantaPay you can start building your wealth
today by lending to other TantaPay users based on your time horizon and risk
tolerance, putting your financial future in your own hands.
</p>
<h3>BORROW</h3>
<p>At TantaPay you can build a fair credit score based on your activity, not someone
else’s metrics, allowing you to borrow money based on your credit worthiness, not
the value of assets you can use as collateral. We allow the market to set the loan
terms, so you can know you are getting the best possible rate. As you build credit,
you can borrow larger amounts of money on better terms, creating a virtuous cycle
of growth for your business.</p>
</div>
</div>

<script>
	$('document').ready(function(){
	$(function(){
		mixpanel.track('View About Us')
	});
</script>
</body>
</html>
{% endblock body_block %}

home_page/templates/home_page/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>TantaPay</title>
	<link href="https://unpkg.com/basscss@7.1.1/css/basscss.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet"> 
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=News+Cycle"> 
	 <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow" rel="stylesheet">
	 <link rel="stylesheet" type="text/css" href="{% static 'js/jquery-3.2.1.min.js' %}">
	<!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init("{{mixpanel}}");</script><!-- end Mixpanel -->

	<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<script src="{% static 'changethewords/jquery.changethewords.js' %}"></script>
<link rel="stylesheet" href="{% static 'changethewords/animate.changethewords.css'%}">
	
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-header">
	<a id="logo" class="brand" href="{% url 'home_page:index' %}"><img src="{% static 'images/tanta.jpg' %}"></a>
</div>
	<ul id=navlist class="nav navbar-nav">
			
		<li><a class="navbar-link" href="{% url 'home_page:about' %}">About Us</a></li>
		<li><a class="navbar-link" href="{% url 'home_page:contact' %}">Contact Us</a></li>
		
		{% if user.is_authenticated %}
		<li><a class= 'navbar-link' href="{% url 'wallet:wallet_summary' %}">My Wallet</a></li>
		<li><a class= 'navbar-link' href="{% url 'home_page:logout' %}">Sign Out</a></li>
		{% else %}
		<li><a class="navbar-link" href="{% url 'home_page:sign_in' %}">Sign In</a></li>
		<li><a class='navbar-link' href="{% url 'home_page:getstart' %}">Get Started</a></li>
		
		{% endif %}
	</ul>
	
</nav>
<br>
<br>
<br>


</body>
{% block body_block %}
{% endblock %}
</html>

home_page/templates/home_page/contact.html
<!DOCTYPE html>
<html>
<head>
	{% extends 'home_page/base.html'%}
</head>
{% block body_block %}
<body>
</div>
</nav>
<div id="jumbo" class="container">
	<div class="jumbotron">
		<h1>Contact Us!</h1>
		<p id="sub">Let us know how we can help you.</p>
	</div>
</div>
<div id="form" class="container">
	<form class="form-group" method='POST'>
	 {{ form.as_p}}
	 {% csrf_token %}

	<!-- <input type="text" class="form-control" placeholder="First Name" name="userfirst">
	<br>

	
	<input type="text" class="form-control" placeholder="Last Name" name="userlast">
	<br>
	
	<input type="email" class="form-control" name="userem" placeholder="Email">
	<br>

	<input type="text" class="form-control" placeholder="Business" name="bus">
	<br>

	<textarea class="form-control" name="comments" rows=5 cols=100 placeholder="Describe your project. What problems are you facing? What ideas do you have already?"></textarea>
	<br> -->
	<button id='button1' type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
<script>
	$('document').ready(function(){
	$(function(){
		mixpanel.track('View Contact Us')
	});
</script>
{% endblock %}	
	
</body>
</html>

home_page/templates/home_page/getstart.html
<!DOCTYPE html>
{% extends "home_page/base.html" %}
{% load staticfiles %}
{% block body_block %}
<script>
{% if messages %}
    {% for message in messages %}
    	alert(message);
    {% endfor %}

{% endif %}
</script>
<div class="container">
<div class='jumbotron'>
	{% if registered %}
		<h1>Thank you for registering!</h1>
	{% else %}
		<h1>Get started with TantaPay today!</h1>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{user_form.as_p}}
			{{profile_form.as_p}}
			<input type="submit" class="btn btn-primary" value="Sign up!">

		</form>
		
	    {% endif %}
<!-- 	    <script>
	$('document').ready(function(){
		$(function(){
			mixpanel.identify()
		});
		$(function(){
			var username = $('#id_username').val()
			var phoneno = $('#id_phone_number').val()
			mixpanel.people.set({
    				"$username": username,
    				"$phone": phoneno,
    				"$created": new Date()});
	});
});
	    </script> -->
</div>
</div>

<script>
	$('document').ready(function(){
	$(function(){
		mixpanel.track('Load Sign Up Page')
	});
</script>


{% endblock body_block %}

home_page/templates/home_page/home.html
{% extends "home_page/base.html" %}
{% load staticfiles %}
{% block body_block %}

<script type="text/javascript">
$('document').ready(function(){
	$(function(){
		mixpanel.track('View Home Page')
	});
    $(function(){
      $("#changethewords").changeWords({
        time: 2000,
        animate: "fadeIn",
        selector: "span",
        repeat: false
      });
    });
    });
  </script>
 
<div class="center py4 my4 white bg-gray bg-cover bg-center" style="background-image: url(https://c1.staticflickr.com/2/1665/24487101292_6a0345feb5_h.jpg); height: 400px; width: 100vw;">
<h1 style="color: #2b2d30; font-family: 'Fjalla One'; font-size: 61px;">Welcome to TantaPay</h1>
	
	<div class="clearfix mxn2 my4 py4" id="changethewords">
	<h2 style="color: #2b2d30;">Imagine a world without 
	<span data-id='1'>banks</span> 
	<span data-id='2'>credit cards</span>
	<span data-id='3'>borders</span>  
	<span data-id='4'>limits.</span></h2>
	</div>
	
</div>

</div>
<div class="center container mt0 rounded" style="background: #ffd468; height: 300px;">
<div class="col-8 px2 mx-auto mt2">
	<h3 class="mt4" style="color: #161515; font-family: 'PT Sans Narrow';">
	At TantaPay, <strong><em>you</em></strong> control your money. There is no minimum balance required in
your wallet, no inactivity fees, and no sales gimmicks to upgrade your service or
increase your fees. Choose the currencies you want to hold in your wallet, and hold
them for as long as you want.
</h3>
<a class="btn btn-default mt3 mb4" href="{% url 'home_page:about' %}" role="button">Learn more</a>

</div>

</div>
</div>
	
	
{% endblock body_block %}		
</body>
</html>

home_page/templates/home_page/onyx.html
<!DOCTYPE html>
{% extends "home_page/base.html" %}
{% load staticfiles %}
<html>
{% block body_block %}
    

<body>

	<div class="container">
		<div class="jumbotron">
			<h1>Why OnyxEngine?</h1>
			<p class="sub">We get it. There are a million and one different business tools out there. However, many of them have 'one size fits all' approach to a unique audience. At Tanta Ventures, we believe that your business tool should be tailored to your business! </p><br>
			<strong><h3>OnyxEngine is:</h3></strong>
			<ul>
				<p>Affordable - Pay for what you use and say goodbye to bloated software with features you never touch!</p>
				<p>Scalable - Your applications grow with your business.</p>
				<p>Secure - All our applications employ the latest security feaures available.</p>
				<p>Totally Customizable - YOU tell us what you want. No salesmen, no gimmicks, just laser-focused business tools.</p>

			</ul>
		</div>


	</div>

</body>
{% endblock body_block %}

home_page/templates/home_page/sign_in.html
<!DOCTYPE html>
{% extends "home_page/base.html" %}
{% block body_block %}

<div class="center container mxn2 mt4 pt4">
	<h1>Please Sign In</h1>
	<form action="{% url 'home_page:sign_in' %}" method="POST">
		{% csrf_token %}
		<input type="text" name="username" placeholder="username">
		<input type="password" name="password">
		<input type="submit" value="Sign In">
	</form>

</div>

<script>
	$('document').ready(function(){
	$(function(){
		mixpanel.track('Load Sign In Page')
	});
</script>
    
{% endblock body_block %}

home_page/templates/home_page/thank_you.html
<!DOCTYPE html>
{% extends "home_page/base.html" %}
{% block body_block %}
    

<html>
<div id=jumbo class="jumbotron">
<div class="container">
<h1>Thank You</h1>
<p>
	We will respond shortly!
</p>
{% endblock body_block %}