Tanta/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from home_page import views
from dashboard import views
from peer2peer import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views

urlpatterns =[
    url(r'^admin/', admin.site.urls),
    url(r'^',include("home_page.urls",namespace='home_page')),
    url(r'^dashboard/',include("dashboard.urls",namespace='dashboard')),
    url(r'^accounts/login/$',views.login,name='login'),
    url(r'^accounts/logout/$',views.logout,name='logout',kwargs={'next_page':'/'}),
    url(r'^wallet/',include("wallet.urls",namespace="wallet")),
    url(r'^peer2peer/',include("peer2peer.urls",namespace="p2p")),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

peer2peer/urls.py
from django.conf.urls import url
from peer2peer import views

urlpatterns=[
	url(r'^$',views.p2p,name='p2phome'),
]

wallet/urls.py
from django.conf.urls import url
from wallet import views

urlpatterns=[
	url(r'^$',views.wallet_summary,name="wallet_summary"),
	url(r'^transfer/$',views.transfer,name='transfer'),
	url(r'^info/$',views.info,name='info'),
	url(r'^forex/$',views.forex,name='forex'),
	url(r'^settings/$',views.settings,name='settings'),
	url(r'^contacts/$',views.contacts,name='contacts'),
	url(r'^peer2peer/$',views.p2p,name='p2p'),
	url(r'^groups/$',views.groups,name='groups'),
	url(r'^contacts/add/$',views.add_contacts,name='add_contact'),
	url(r'^info/reset/$',views.passreset,name='pword'),
	url(r'^groups/display_groups/$',views.display_groups,name='display_groups'),
	url(r'^contacts/verify/$',views.send_contacts,name='verify_contact'),
	url(r'^groups/group_limit/$',views.group_limit,name='group_limit'),
	url(r'^groups/remove/$',views.group_remove,name='group_remove'),
	url(r'^groups/create/$',views.create_group,name='group_create'),
	url(r'^contacts/details/$',views.contact_detail,name='contact_detail'),
	url(r'^contacts/remove/$',views.contact_remove,name='contact_remove'),

]

peer2peer/models.py
from django.db import models

# Create your models here.

peer2peer/views.py
from django.shortcuts import render

# Create your views here.
def p2p(request):
	return render(request,"p2p.html")

peer2peer/templates/peer2peer/base.html
<!DOCTYPE html>
{% load staticfiles %}
<link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Catamaran:800" rel="stylesheet"> 

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=News+Cycle" >
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init("{{mixpanel}}");</script><!-- end Mixpanel -->
<link rel="stylesheet" type="text/css" href="{% static 'css/master.css%}">
<script src="{% static 'js/jquery.avgrund.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/avgrund.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'css/bss.css' %}">
<script scr='{% static " js/myscript.js" %}'></script>
<html>
<head>
	<title>
		Tanta Peer to Peer
	</title>
</head>
<body>
<nav class="navbar navbar-default">
<div class="navbar-header">
</div>
	<ul id=navlist class="nav navbar-nav">
	
		<li><a class="navbar-link" href="{% url 'wallet:wallet_summary' %}">My Wallet</a></li>
		<li>
		<div class='realative inline block'>
			  <button type="button" class="btn btn-big mt1 p4" id='menu' style=" background-color: #f9f9f9;">
			    Actions &#9662;
			  </button>
			  <div class="clearfix" style="display: none; position: absolute; background-color: #f9f9f9;" id='dropdown-content'>
			    <a href="{% url 'wallet:transfer' %}" class="btn block" style='color: black;'>Transfer</a>
			    <a href="{% url 'wallet:forex' %}"" class="btn block" style='color: black;'>Currency Exchange</a>
			    <a href="{% url 'wallet:contacts' %}" class="btn block" style='color: black;'>Manage Contacts</a>
			    <a href="{% url 'wallet:p2p' %}" class="btn block " style='color: black;'>Borrow or Lend</a>
			    <a href="{% url 'wallet:settings' %}?next={{ request.path|urlencode }}" class="btn block " style='color: black;'>Settings</a>
			  </div>
			</div></li>
		<li><a class="navbar-link" href="{% url 'wallet:info' %}">My Info</a></li>
		<li><a class= 'navbar-link' href="{% url 'dashboard:logout' %}">Sign Out</a></li>
		</ul>
		</nav>
<br>
</body>
<script>
	$(document).ready(function(){
		$('#menu').hover(function(){
			$('#dropdown-content').toggle();
			$('#dropdown-content').mouseenter(function(){
				$(this).show();
			});
			$('#dropdown-content').mouseleave(function(){
				$(this).hide();
			});
		});
	})
</script>
</html>
{% block content %}
{% endblock content %}

peer2peer/templates/peer2peer/p2p.html
{% extends "wallet/base.html" %}

{% block content %}
<h1 class='center container'>Under Construction...</h1>
<h3 class='center'>Your credit score is</h3>

<script>
	$(document).ready(function(){
		$(this).avgrund({
			openOnEvent: false,
			showClose: true,
			showCloseText: 'X',
			closeByDocument: true,
			template: "<div class='mt4 center' style='top: 100px;'><h3 id='modal'>Welcome to TantaPay Peer to Peer lending!</h3><br><p style='top: 60px;'>Let's take a quick tour to learn how things work...</p></div><a id='fxbtn' class='close' role='button' style='position: absolute; top: 230px; left: 300px;'>next</a><a id='closebtn' class='close' role='button' style='position: absolute; top: 230px; left: 300px; display: None;'>close</a>"
		});
		$('#fxbtn').click(function(){
			$('#modal').text("Peer to Peer Lending is simple!");
			$('p').text("It's like borrowing money from a friend");
			$(this).hide();
			$('#closebtn').show();
		});
		$('#closebtn').click(function(){
			$(this).attr('class','avgrund-close');
		});
	});

</script>
{% endblock content %}